// api/analyze.js
import OpenAI from "openai";
import crypto from "crypto";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export default async function handler(req, res) {
  console.log("🟢 [analyze.js] API hit");

  if (req.method !== "POST") {
    console.log("🚫 Wrong method:", req.method);
    return res.status(405).json({ error: "Use POST" });
  }

  const auth = req.headers.authorization || "";
  const token = auth.replace("Bearer ", "");
  const expected = process.env.GITHUB_API_KEY;

  if (!expected || token !== expected) {
    console.log("❌ Unauthorized request");
    return res.status(401).json({ error: "Unauthorized" });
  }

  const { text } = req.body || {};
  console.log("📩 Received text:", text ? text.slice(0, 200) : "❌ No text provided");

  if (!text) {
    return res.status(400).json({ error: "Missing text" });
  }

  try {
    const prompt = `
Analyze the swim workout below. Return two things:
1️⃣ A formatted human-readable breakdown (clear and structured).
2️⃣ A valid JSON object summarizing the totals.

Your JSON MUST follow this schema:
<JSON>
{
  "totalYards": number,
  "durationMinutes": number,
  "sectionYards": {
    "Warmup": number,
    "Kick": number,
    "Drill": number,
    "Main Set": number,
    "Pull": number,
    "Sprint Finisher": number,
    "Cool Down": number
  },
  "strokePercentages": {
    "Freestyle": number,
    "Backstroke": number,
    "Breaststroke": number,
    "Butterfly": number,
    "Drill": number,
    "Kick": number
  },
  "aiTip": string
}
</JSON>

Then output the formatted text clearly below it.
Workout text:
"""${text}"""
    `;

    console.log("🤖 Sending request to OpenAI...");
    const response = await client.responses.create({
      model: "gpt-4o-mini",
      input: prompt,
      max_output_tokens: 1200,
    });

    const content = response.output_text || "";
    console.log("🧠 Raw AI response:\n", content.slice(0, 500));

    let json = {};
    let formattedText = content.trim();

    const jsonMatch = content.match(/<JSON>([\s\S]*?)<\/JSON>/i);
    if (jsonMatch) {
      try {
        json = JSON.parse(jsonMatch[1]);
        formattedText = content.replace(/<JSON>[\s\S]*?<\/JSON>/i, "").trim();
        console.log("✅ JSON parsed successfully");
      } catch (err) {
        console.error("❌ JSON parse error:", err);
      }
    } else {
      console.warn("⚠️ No JSON block found in AI output.");
    }

    console.log("📊 Parsed result:", json);

    res.status(200).json({
      id: crypto.randomUUID(),
      date: new Date().toISOString(),
      formattedText,
      aiSummary: "Generated by OpenAI analysis",
      distanceYards: json.totalYards || 0,
      durationMinutes: json.durationMinutes || 0,
      sectionYards: json.sectionYards || {},
      strokePercentages: json.strokePercentages || {},
      aiTip: json.aiTip || "No AI tip generated.",
    });
  } catch (err) {
    console.error("🔥 Error in /api/analyze:", err);
    res.status(500).json({ error: err.message || "Server error" });
  }
}
