// api/analyze.js
export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Use POST" });
  }

  // Authorization check using your GitHub key (for private use)
  const expected = process.env.GITHUB_API_KEY;
  const auth = req.headers.authorization || "";
  const token = auth.replace("Bearer ", "");
  if (!expected || token.trim() !== expected.trim()) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  const { text } = req.body || {};
  if (!text) return res.status(400).json({ error: "Missing text" });

  const OPENAI_KEY = process.env.OPENAI_API_KEY;
  if (!OPENAI_KEY) {
    return res.status(500).json({ error: "Missing OPENAI_API_KEY in environment" });
  }

  // Build the structured prompt
  const prompt = `
You are a professional swim coach and analyst. The user will send a swim workout written as text.

Your job:
1. Parse the workout text carefully.
2. Detect all sections (Warmup, Kick, Drill, Main Set, Pull, Sprint, Cool Down, etc.).
3. For each section, show every set line-by-line and calculate yardage.
4. Add total yardage for each section.
5. Then calculate total practice yardage, a section summary table (% of total), and a stroke/drill mix.
6. End with a 1–2 sentence coaching summary.

Use this exact structure:
🏊‍♂️ Workout Breakdown
[Each section with lines and calculated yards]

🧮 TOTAL YARDAGE
[List of section totals + grand total]

🏁 SECTION SUMMARY
Section	Yards	% of Total

🧠 STROKE + DRILL MIX
Type	Yards	% of Total

✅ Summary
1–2 sentences summarizing the practice.

Here is the workout text to analyze:
---
${text}
---
Return only plain text formatted exactly in that style (no JSON or markdown).
  `;

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${OPENAI_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.4
      })
    });

    const data = await response.json();

    if (!data.choices || !data.choices[0]) {
      return res.status(500).json({ error: "AI response missing", raw: data });
    }

    const formattedText = data.choices[0].message.content.trim();

    // Send structured JSON so your app can display it
    res.status(200).json({
      id: crypto.randomUUID(),
      date: new Date().toISOString(),
      formattedText,
      aiSummary: "Generated by OpenAI analysis"
    });
  } catch (err) {
    console.error("AI error:", err);
    res.status(500).json({ error: "AI request failed", details: err.message });
  }
}
